apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: aksdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: aksdemo 
    spec:
      containers:
        - name: aksdemo 
          image: demoe2e.azurecr.io/aksdemo 
          imagePullPolicy: Always
          ports:
          - containerPort: 80
