on: [push] 

 

jobs: 

  build: 

    runs-on: ubuntu-latest 

    steps: 

    - uses: actions/checkout@master 

     

    # Connect to Azure Container registry (ACR) 

    - uses: azure/docker-login@v1 

      with: 

        login-server: demoaksgithub.azurecr.io 

        username: ${{ secrets.REGISTRY_USERNAME }}  

        password: ${{ secrets.REGISTRY_PASSWORD }} 

     

    # Docker build and push to a Azure Container registry (ACR) 

    - run: | 

        docker build . -t demoaksgithub.azurecr.io/k8sdemo:${{ github.sha }} 

        docker push demoaksgithub.azurecr.io/k8sdemo:${{ github.sha }} 

     

    # Set the target AKS cluster.  

    - uses: azure/aks-set-context@v1 

      with: 

        creds: '${{ secrets.AZURE_CREDENTIALS }}' 

        cluster-name: AKSdemo 

        resource-group: shirispire 

     

    # Create imagepullsecret for Azure Container registry (ACR) 

    - uses: azure/k8s-create-secret@v1 

      with: 

        container-registry-url: demoaksgithub.azurecr.io 

        container-registry-username: ${{ secrets.REGISTRY_USERNAME }} 

        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }} 

        secret-name: demo-k8s-secret 

        namespace: demo 

     

    # Deploy app to AKS 

    - uses: azure/k8s-deploy@v1 

      with: 

        manifests: | 

          ./.github/shirihhhh/aks1/manifests/deployment.yml 

          ./.github/shirihhhh/aks1/manifests/service.yml 

        images: | 

          demoaksgithub.azurecr.io/k8sdemo:${{ github.sha }} 

        imagepullsecrets: | 

          demo-k8s-secret 

          namespace: demo 
